// components/dashboard/exams/report-templates/BasicSchoolReportCard.tsx

import React from 'react';
import { 
  Document, 
  Page, 
  Text, 
  View, 
  StyleSheet,
  Image
} from '@react-pdf/renderer';
import { ReportCardProps } from './ReportTypes';
import { BasicSchoolHeader } from './BasicSchoolHeader';
import { StudentInfoSection } from './StudentInfoSection';
import { SubjectsTable } from './SubjectsTable';
import { AttendanceSection } from './AttendanceSection';
import { SummarySection } from './SummarySection';
import { CommentsSection } from './CommentsSection';
import { BehaviorSection } from './BehaviorSection';
import { SignatureSection } from './SignatureSection';
import { RemarksSection } from './remarks';
import { GradingKey } from './GradingKey';
import { formatReportDate } from '@/lib/services/reportUtils';

// Create styles
const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 10,
    fontFamily: 'Helvetica',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 8,
    color: '#666',
  },
});

export const BasicSchoolReportCard: React.FC<ReportCardProps> = ({ 
  schoolInfo, 
  studentInfo, 
  academicInfo, 
  subjects, 
  attendance, 
  behaviors, 
  comments,
  totalAverage,
  showLogo = true,
}) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header with school info */}
        <BasicSchoolHeader 
          schoolInfo={schoolInfo} 
          showLogo={showLogo} 
          title="Basic School Terminal Report Card" 
        />

        {/* Student Information */}
        <StudentInfoSection 
          studentInfo={studentInfo} 
          academicInfo={academicInfo} 
          formatDate={formatReportDate} 
        />

        {/* Attendance Information */}
        {attendance && <AttendanceSection attendance={attendance} />}

        {/* Subject Results Table */}
        <SubjectsTable 
          subjects={subjects}
          showClassScores={true}
          showExamScores={true}
          showPositions={true}
        />

        {/* Summary Section */}
        <SummarySection 
          studentInfo={studentInfo}
          subjects={subjects}
          totalAverage={totalAverage}
          passMarkPercentage={40}
        />

        {/* Behavior/Conduct Section */}
        {behaviors && behaviors.length > 0 && (
          <BehaviorSection behaviors={behaviors} />
        )}

        {/* Comments Section */}
        {comments && (
          <CommentsSection comments={comments} />
        )}

        {/* Remarks Section */}
        <RemarksSection />

        {/* Grading Key */}
        <GradingKey schoolType="basic" />

        {/* Signature Section */}
        <SignatureSection 
          showParentSignature={true}
        />

        {/* Footer */}
        <View style={styles.footer}>
          <Text>Generated by EduTrac School Management System | {new Date().toLocaleDateString()}</Text>
        </View>
      </Page>
    </Document>
  );
};
